seed: 18
verbose: 2

# Data params
rows_per_frame: 543
max_len_frames: 384
max_len_phrase: 43
pad_frames: -100.
pad_phrase: 61
num_classes: 62

n_splits: 10

fold: 0
train:
    batch_size: 512
    drop_remainder: True
    augment: True
    shuffle: True
    repeat: False

val:
    batch_size: 512
    drop_remainder: True
    augment: False
    shuffle: False
    repeat: False

# Model params
n_epochs: 300
dim: 384
drop_rate: 0
ksize: 34
bn_momentum: 0.95
expand: 2
activation: 'gelu' # swish, relu
num_heads: 4

loss:
    name: 'SCCE_loss'
    label_smoothing: 0 
    
# loss:
#     name: 'SCCE_loss_with_smoothing'
#     label_smoothing: 0.2
    
scheduler:
    name: 'cosine_cycle'
    warmup: 0
    lr_min: 1e-6
    lr_max: 1e-3
    wd_ratio: 0.1
    num_cycles: 0.5

# scheduler:
#     name: 'one_cycle'
#     warmup: 0
#     lr_min: 1e-6
#     lr_max: 1e-3
#     weight_decay: 0.1
#     decay_type: 'cosine'
    
optimizer:
    name: 'adam'
  
# optimizer:
#     name: 'radam'
#     sma_threshold: 4
#     sync_period: 5

callbacks:
    - 'logger_cb'
    - 'ckpt_cb'
    - 'lr_cb'
    - 'wd_cb'
    

# Output
output_dir: '/home/rafiz/kaggle_asl_fingerspelling_competition/results/'
experiment: 'config1'


    